import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation
        'nav.home': 'Home',
        'nav.about': 'About',
        'nav.services': 'Services',
        'nav.training': 'Training',
        'nav.transformations': 'Transformations',
        'nav.xpSystem': 'XP System',
        'nav.contact': 'Contact',

        // Home Page
        'home.levelUp': 'Level Up',
        'home.yourLife': 'Your Life',
        'home.withCoach': 'With Coach Moumen',
        'home.heroSubtitle': 'Transform your fitness journey into an epic adventure',
        'home.startJourney': 'Start Your Journey',
        'home.viewPrograms': 'View Programs',
        'home.statsTitle': 'Your Stats',
        'home.totalXpGained': 'Total XP Gained',
        'home.activeWarriors': 'Active Warriors',
        'home.successRate': 'Success Rate',
        'home.bossBattlesWon': 'Boss Battles Won',
        'home.readyToLevel': 'Ready to Level Up?',
        'home.joinUs': 'Join thousands of warriors',
        'home.viewLeaderboard': 'View Leaderboard',
        'home.new': 'NEW!',
        'home.quest.title': 'Current Quest',
        'home.quest.level1': 'LEVEL 1',
        'home.quest.streak': 'Daily Workout Streak',
        'home.quest.nutrition': 'Nutrition Goals',
        'home.quest.perfectForm': '🎯 Perfect Form',
        'home.quest.strength': '💪 Strength +10',
        'home.quest.speed': '⚡ Speed +5',
        'home.experience.title': 'Experience',
        'home.experience.the': 'The',
        'home.experience.journey': 'Journey',
        'home.experience.desc': 'Discover how our gamified fitness system transforms your workout experience into an epic adventure of personal growth and achievement.',
        'home.feature.tracking': 'Smart Progress Tracking',
        'home.feature.trackingDesc': 'Advanced analytics to monitor your fitness journey in real-time',
        'home.feature.achievements': 'Achievement System',
        'home.feature.achievementsDesc': 'Earn rewards and unlock special perks as you reach new milestones',
        'home.feature.coaching': 'Personalized Coaching',
        'home.feature.coachingDesc': 'Get expert guidance tailored to your unique fitness goals',
        'home.quote.text': 'In the game of fitness, every rep is a power-up, every set is a level, and every workout is a boss fight. Are you ready to become the main character of your story?',
        'home.quote.author': '- Coach Moumen',
        'home.badge.elite': 'Elite Trainer',
        'home.badge.master': 'Fitness Master',
        'home.badge.level100': 'Level 100',

        // About Page
        'about.title': 'About Coach Moumen',
        'about.subtitle': 'Your Guide to the Next Level',
        'about.story': 'My Story',
        'about.storyText1': 'My journey began not in a gym, but with a desire to understand human potential. As a graduate of the Faculty of Physical Education at Mansoura University, I combined academic rigor with practical application.',
        'about.storyText2': 'Over the years, I\'ve evolved from a local trainer to a Branch Manager at top gyms, always driven by one goal: to help others unlock their true strength.',
        'about.philosophy': 'Training Philosophy',
        'about.philosophy.scientific': 'Scientific Approach',
        'about.philosophy.scientificDesc': 'Evidence-based training methods geared for maximum efficiency and safety.',
        'about.philosophy.mindset': 'Mindset First',
        'about.philosophy.mindsetDesc': 'Building mental resilience is just as important as physical strength.',
        'about.philosophy.sustainable': 'Sustainable Results',
        'about.philosophy.sustainableDesc': 'Creating lifestyle changes that last a lifetime, not just a season.',
        'about.philosophy.holistic': 'Holistic Growth',
        'about.philosophy.holisticDesc': 'Focusing on health, performance, and aesthetics in perfect balance.',
        'about.experience': 'Experience',
        'about.certifications': 'Certifications',
        'about.education': 'Education',
        'about.education.degree': 'Physical Education',
        'about.education.school': 'Faculty of Physical Education - Mansoura University',
        'about.education.desc': 'specialized in Sports Management',

        // About - Timeline
        'about.timeline.branchManager': 'Branch Manager',
        'about.timeline.branchManagerDesc': 'Leading operations at Elegant and N13 Gyms, overseeing facility management and team development.',
        'about.timeline.fitnessManager': 'Fitness Manager',
        'about.timeline.fitnessManagerDesc': 'Managing fitness operations and client success at Doctor and Coach.',
        'about.timeline.fitnessMgmt': 'Fitness Management',
        'about.timeline.fitnessMgmtDesc': 'Advanced to Fitness Manager at Dr and Coach, expanding into Personal Training roles at N13 and Elegant Gyms.',
        'about.timeline.coaching': 'Professional Coaching',
        'about.timeline.coachingDesc': 'Gained diverse experience across B1 Gym and Mego Gym, progressing to Operations Manager.',
        'about.timeline.founder': 'Well and Fit Founder',
        'about.timeline.founderDesc': 'Established Well and Fit while serving as Vice Head of Education Committee.',
        'about.timeline.online': 'Online Training Launch',
        'about.timeline.onlineDesc': 'Started online personal training services, reaching clients globally.',

        // About - Certifications
        'about.cert.strength': 'Strength & Conditioning Specialist',
        'about.cert.strengthDesc': 'Approved by TASS, certified through PBLS Academy, endorsed by Egyptian Federation of Sport Culture.',
        'about.cert.nutrition': 'Sport Nutrition Coach',
        'about.cert.nutritionDesc': 'Advanced sports nutrition principles and meal planning',
        'about.cert.weight': 'Weight Management',
        'about.cert.weightDesc': 'Specialized strategies for sustainable weight loss and body composition',
        'about.cert.cpr': 'CPR & First Aid',
        'about.cert.cprDesc': 'Certified by Egyptian Red Crescent',

        // Services Page
        'services.title': 'Choose Your Path',
        'services.subtitle': 'Select your training tier and unlock your full potential',
        'services.instantStart': 'Instant Start',
        'services.provenResults': 'Proven Results',
        'services.support247': '24/7 Support',
        'services.mostPopular': 'MOST POPULAR',
        'services.bestValue': 'BEST VALUE',
        'services.whatsIncluded': "What's Included",
        'services.startQuest': 'Start Your Quest',
        'services.xpBonus': 'XP Bonus',
        'services.customQuest': 'Need Something Custom?',
        'services.customDescription': "Let's craft a unique training protocol tailored specifically to your goals, schedule, and preferences.",
        'services.createCustom': 'Create Custom Quest',
        'services.warriorsTrained': 'Warriors Trained',
        'services.yearsExperience': 'Years Experience',

        // Plans
        'plans.1month': '1 Month Quest',
        'plans.1monthSub': 'Begin Your Legend',
        'plans.3months': '3 Months Protocol',
        'plans.3monthsSub': 'Forge Your Power',
        'plans.6months': '6 Months System',
        'plans.6monthsSub': 'Master Your Destiny',
        'plans.12months': '12 Months Legendary',
        'plans.12monthsSub': 'Become Immortal',
        'plans.novice': 'Novice',
        // Plans Details
        'plans.1month.desc': 'The perfect starting point for aspiring fitness warriors. Master the fundamentals and build your foundation.',
        'plans.3months.desc': 'Intermediate program with advanced training techniques and regular personalized coaching support.',
        'plans.6months.desc': 'Comprehensive coaching for dedicated athletes with premium support and advanced programming.',
        'plans.12months.desc': 'The ultimate VIP experience with unlimited access, daily coaching, and exclusive benefits for maximum results.',

        // Plan Features
        'plans.feature.customProgram': 'Customized Training Program',
        'plans.feature.nutrition': 'Detailed Nutrition Guide',
        'plans.feature.tracking': 'Weekly Progress Tracking',
        'plans.feature.community': 'WhatsApp Community Access',
        'plans.feature.tutorials': 'Video Form Tutorials',
        'plans.feature.advancedPlans': 'Advanced Training Plans',
        'plans.feature.mealPlans': 'Personalized Meal Plans',
        'plans.feature.checkins2x': '2x Weekly Check-ins',
        'plans.feature.analysis': 'Video Form Analysis',
        'plans.feature.support247': '24/7 WhatsApp Support',
        'plans.feature.eliteProg': 'Elite Custom Programming',
        'plans.feature.advancedNut': 'Advanced Nutrition Planning',
        'plans.feature.calls3x': '3x Weekly Coaching Calls',
        'plans.feature.vipSupport': 'Priority VIP Support',
        'plans.feature.recovery': 'Recovery & Sleep Guide',
        'plans.feature.legendaryPlans': 'Legendary Custom Plans',
        'plans.feature.dailyCoaching': 'Daily Personal Coaching',
        'plans.feature.eliteRecovery': 'Elite Recovery System',
        'plans.feature.privateLine': 'Private WhatsApp Line',
        'plans.feature.vipBenefits': 'Exclusive VIP Benefits',
        'plans.feature.bodyAnalysis': 'Monthly Body Analysis',

        // Coach Profile
        'coach.badges': 'Badges',
        'coach.stats': 'Stats',
        'coach.badge.master': 'Master Trainer',
        'coach.badge.masterDesc': 'Legendary status achieved through years of dedication',
        'coach.badge.strength': 'Strength Sage',
        'coach.badge.strengthDesc': 'Expert in strength and conditioning',
        'coach.badge.nutrition': 'Nutrition Oracle',
        'coach.badge.nutritionDesc': 'Master of performance nutrition',
        'coach.badge.transformation': 'Transformation Guru',
        'coach.badge.transformationDesc': 'Specialist in complete body transformations',
        'coach.badge.quest': 'Quest Master',
        'coach.badge.questDesc': 'Creator of epic fitness challenges',
        'coach.stat.strength': 'Strength',
        'coach.stat.strengthDesc': 'Master of power and form',
        'coach.stat.agility': 'Agility',
        'coach.stat.agilityDesc': 'Swift and precise movements',
        'coach.stat.endurance': 'Endurance',
        'coach.stat.enduranceDesc': 'Unstoppable stamina',
        'coach.stat.wisdom': 'Wisdom',
        'coach.stat.wisdomDesc': 'Elite coaching knowledge',
        'coach.unlockReq': 'Unlock Requirement',
        'coach.achieve.warriors': 'Warriors Trained',
        'coach.achieve.bossFights': 'Boss Fights Won',
        'coach.achieve.success': 'Success Rate',
        'coach.achieve.xp': 'Experience Points',
        'coach.achieve.years': '8+ Years',
        'coach.move.form': 'Perfect Form Master',
        'coach.move.formDesc': 'Execute exercises with flawless precision',
        'coach.move.nutrition': 'Nutrition Strategist',
        'coach.move.nutritionDesc': 'Craft optimal fuel plans for peak performance',
        'coach.move.mind': 'Mind-Body Sync',
        'coach.move.mindDesc': 'Achieve perfect harmony of mental and physical power',
        'coach.move.motivation': 'Motivation Amplifier',
        'coach.move.motivationDesc': 'Boost warrior spirits to new heights',
        'coach.title': 'Profile',
        'coach.role': 'MA Coach',
        'coach.expTitle': 'Experience',

        // Plan Highlights
        'plans.highlight.beginners': 'Perfect for beginners',
        'plans.highlight.foundation': 'Foundation building',
        'plans.highlight.popular': 'Most popular choice',
        'plans.highlight.transformations': 'Real transformations',
        'plans.highlight.athletes': 'For serious athletes',
        'plans.highlight.complete': 'Complete transformation',
        'plans.highlight.bestValue': 'Best value',
        'plans.highlight.vip': 'VIP treatment',

        // Training Page
        'training.title': 'Epic Missions',
        'training.beta': 'BETA',
        'training.subtitle': 'Embark on your fitness journey through gamified workouts and challenges',
        'training.dailyQuests': 'Daily Quests',
        'training.dailyQuestsDesc': 'Quick daily workouts',
        'training.bossBattles': 'Boss Battles',
        'training.bossBattlesDesc': 'Intense challenges',
        'training.achievementHunt': 'Achievement Hunt',
        'training.achievementHuntDesc': 'Unlock rewards',
        'training.skillTree': 'Skill Tree',
        'training.skillTreeDesc': 'Progress tracking',
        'training.launchingSoon': 'Launching Soon',
        'training.launchingDesc': 'Get ready for an epic fitness adventure! Join our community to be the first to access exclusive missions and rewards.',
        'training.joinCommunity': 'Join Community',
        'training.phase1': 'Phase 1 Development',

        // Transformations Page
        'transformations.title': 'Players Leaderboard',
        'transformations.subtitle': 'Witness the epic transformations of our legendary players',
        'transformations.journeyDetails': 'Journey Details',
        'transformations.program': 'Program',
        'transformations.testimonial': 'Testimonial',
        'transformations.achievements': 'Achievements',
        'transformations.tapToSee': 'Tap to see journey details',
        'transformations.tapToFlip': 'Tap to see transformation',
        'transformations.before': 'BEFORE',
        'transformations.after': 'AFTER',
        // Transformation Data Keys
        'transformations.program.elite': 'Elite Performance System',
        'transformations.program.warrior': 'Warrior Training Protocol',
        'transformations.program.legendary': 'Legendary Transformation',
        'transformations.achieve.champion': 'Elite Champion',
        'transformations.achieve.master': 'Transformation Master',
        'transformations.achieve.warrior': 'Elite Warrior',
        'transformations.achieve.legend': 'Fitness Legend',
        'transformations.achieve.king': 'Dedication King',
        'transformations.achieve.star': 'Rising Star',
        'transformations.badge.weight': 'Weight Warrior',
        'transformations.badge.consistency': 'Consistency King',
        'transformations.badge.elite': 'Transformation Elite',
        'transformations.badge.muscle': 'Muscle Builder',
        'transformations.badge.fatLoss': 'Fat Loss Champion',
        'transformations.testi.1': 'The transformation journey was incredible. The gaming approach made every workout exciting!',
        'transformations.testi.2': 'Amazing results with the structured program. Achieved more than I thought possible!',
        'transformations.testi.3': 'The program transformed not just my body, but my entire lifestyle!',

        // XP System Page
        'xp.title': 'XP System',
        'xp.subtitle': 'Track your progress and unlock rewards',
        'xp.levelsAndTitles': 'Levels & Titles',
        'xp.howToEarnXp': 'How to Earn XP',
        'xp.earnXp': 'Earn XP',
        'xp.levelUp': 'Level Up',
        'xp.unlockRewards': 'Unlock Rewards',
        'xp.viewArsenal': 'View Full Arsenal',
        'xp.scroll': 'Scroll',
        'xp.currentLevel': 'Current Level',
        'xp.reward': 'Reward',
        'xp.rule1': 'Start at Level 1 when you subscribe to any package',
        'xp.rule2': 'Each package grants you XP to help you progress',
        'xp.rule3': 'Every 10 levels, unlock a new title and special rewards',
        'xp.rule4': 'Track your progress and compete with others on our Leaderboard',
        'xp.heroTitle': 'MA Warrior Journey',
        'xp.heroSubtitle': 'Welcome to MA Fitness, where your fitness journey transforms into a real gameplay experience!',
        'xp.benefitsTitle': 'Why Level Up?',
        'xp.benefit1': 'Exclusive titles displayed on the Global Leaderboard',
        'xp.benefit2': 'Free T-shirt or Hoodie every 10 levels',
        'xp.benefit3': 'Higher levels = More strength and determination',
        'xp.benefit4': 'Chance to appear among MA Fitness\'s top players',
        'xp.ctaTitle': 'Ready to Begin Your Journey?',
        'xp.ctaSubtitle': 'View our complete arsenal of training packages and choose the perfect path for your fitness quest.',
        // Level Tier Titles
        'xp.tier.fitnessNovice': 'Fitness Novice',
        'xp.tier.maWarrior': 'MA Warrior',
        'xp.tier.eliteTrainee': 'Elite Trainee',
        'xp.tier.maLegend': 'MA Legend',
        'xp.tier.fitnessLeader': 'Fitness Leader',
        'xp.tier.maKnight': 'MA Knight',
        'xp.tier.victoryMaster': 'Victory Master',
        'xp.tier.maChampion': 'MA Champion',
        'xp.tier.fitnessBeast': 'Fitness Beast',
        'xp.tier.maLegendElite': 'MA Legend Elite',
        'xp.tier.supremeWarrior': 'Supreme Warrior',
        'xp.tier.captainMA': 'Captain MA',
        // Level Tier Rewards
        'xp.reward.gaining': 'Gaining exercise experience',
        'xp.reward.warriorTshirt': 'Special MA Warrior T-shirt',
        'xp.reward.hoodie': 'MA Hoodie for distinguished players',
        'xp.reward.specialTshirt': 'Special Edition MA T-shirt',
        'xp.reward.limitedHoodie': 'Limited Edition MA Hoodie',
        'xp.reward.newDesign': 'New Design MA T-shirt',
        'xp.reward.levelHoodie': 'Level-specific MA Hoodie',
        'xp.reward.exclusiveTshirt': 'Exclusive Design MA T-shirt',
        'xp.reward.champHoodie': 'Champions MA Hoodie',
        'xp.reward.topTshirt': 'Top-tier MA T-shirt',
        'xp.reward.vipHoodie': 'VIP Edition MA Hoodie',
        'xp.reward.captain': 'Exclusive to Captain Moumen (MA)',

        // Contact Page
        'contact.joinAdventure': 'Join The Adventure',
        'contact.heroSubtitle': 'Connect with Coach Moumen and start your fitness journey today',
        'contact.title': 'Contact Us',
        'contact.partnerOrJoin': 'Partner with us or join our team',
        'contact.startApplication': 'Start Application',
        'contact.yourName': 'Your Name',
        'contact.email': 'Email',
        'contact.phone': 'Phone',
        'contact.message': 'Your Message',
        'contact.requestType': 'Request Type',
        'contact.partnership': 'Partnership',
        'contact.jobApplication': 'Job Application',
        'contact.position': 'Position Applied For',
        'contact.experience': 'Years of Experience',
        'contact.submit': 'Submit Application',
        'contact.sending': 'Sending...',
        'contact.followUs': 'Follow Us',
        'contact.followCoach': 'Follow Coach Moumen',
        'contact.phName': 'Enter your name',
        'contact.phEmail': 'Enter your email',
        'contact.phPhone': 'Enter your phone number',
        'contact.phPosition': 'Enter the position you\'re applying for',
        'contact.phExperience': 'Enter your years of experience',
        'contact.phMessageJob': 'Tell us about your experience and why you\'d be a great fit',
        'contact.phMessagePartner': 'Tell us about your partnership idea',
        'contact.resume': 'Resume/CV',
        'contact.success': 'Your message has been sent successfully! We will contact you soon.',
        'contact.error': 'There was an error sending your message. Please try again.',

        // Footer
        'footer.poweredBy': 'Powered by',
        'footer.allRights': 'All Rights Reserved',
        'footer.coachName': 'Coach Moumen',
        'footer.quickLinks': 'Quick Links',
        'footer.followUs': 'Follow Us',

        // App Coming Soon Section
        'app.title1': 'NEW QUEST',
        'app.title2': 'UNLOCKING',
        'app.subtitle': 'Your pocket-sized training companion is loading...',
        'app.levelUp': 'LEVEL UP',
        'app.fitnessApp': 'FITNESS APP',
        'app.loading': 'LOADING...',
        'app.progressXp': 'Progress XP',
        'app.progressXpDesc': 'Track your level ups',
        'app.achievements': 'Achievements',
        'app.achievementsDesc': 'Unlock epic rewards',
        'app.downloadOn': 'Download on',
        'app.appStore': 'App Store',
        'app.getItOn': 'Get it on',
        'app.googlePlay': 'Google Play',
        'app.soon': 'SOON',
        'app.getLaunchNotification': 'Get Launch Notification',
        'app.enterEmail': 'Enter your email',
        'app.notifyMe': 'NOTIFY ME',
        'app.achievementUnlocked': 'ACHIEVEMENT UNLOCKED!',
        'app.firstToKnow': "You'll be first to know when we launch",

        // Common
        'common.learnMore': 'Learn More',
        'common.viewAll': 'View All',
        'common.getStarted': 'Get Started',
        'common.contactUs': 'Contact Us',
    },
    ar: {
        // Navigation
        'nav.home': 'الرئيسية',
        'nav.about': 'عن المدرب',
        'nav.services': 'الخدمات',
        'nav.training': 'التدريب',
        'nav.transformations': 'التحولات',
        'nav.xpSystem': 'نظام XP',
        'nav.contact': 'تواصل معنا',

        // Home Page
        'home.levelUp': 'ارتقِ',
        'home.yourLife': 'بحياتك',
        'home.withCoach': 'مع الكابتن مؤمن',
        'home.heroSubtitle': 'حوّل رحلة لياقتك إلى مغامرة ملحمية',
        'home.startJourney': 'ابدأ رحلتك',
        'home.viewPrograms': 'عرض البرامج',
        'home.statsTitle': 'إحصائياتك',
        'home.totalXpGained': 'إجمالي نقاط الخبرة',
        'home.activeWarriors': 'المحاربون النشطون',
        'home.successRate': 'معدل النجاح',
        'home.bossBattlesWon': 'معارك الزعماء المنتصرة',
        'home.readyToLevel': 'مستعد للارتقاء؟',
        'home.joinUs': 'انضم لآلاف المحاربين',
        'home.viewLeaderboard': 'عرض لوحة المتصدرين',
        'home.new': 'جديد!',
        'home.quest.title': 'المهمة الحالية',
        'home.quest.level1': 'المستوى 1',
        'home.quest.streak': 'سلسلة التمارين اليومية',
        'home.quest.nutrition': 'أهداف التغذية',
        'home.quest.perfectForm': '🎯 أداء مثالي',
        'home.quest.strength': '💪 قوة +10',
        'home.quest.speed': '⚡ سرعة +5',
        'home.experience.title': 'جرب',
        'home.experience.the': '',
        'home.experience.journey': 'الرحلة',
        'home.experience.desc': 'اكتشف كيف يحول نظام اللياقة البدنية بأسلوب الألعاب الخاص بنا تجربة التمرين إلى مغامرة ملحمية من النمو الشخصي والإنجاز.',
        'home.feature.tracking': 'تتبع التقدم الذكي',
        'home.feature.trackingDesc': 'تحليلات متقدمة لمراقبة رحلة لياقتك في الوقت الفعلي',
        'home.feature.achievements': 'نظام الإنجازات',
        'home.feature.achievementsDesc': 'اربح مكافآت وافتح ميزات خاصة مع وصولك إلى مراحل جديدة',
        'home.feature.coaching': 'تدريب مخصص',
        'home.feature.coachingDesc': 'احصل على توجيه الخبراء المصمم خصيصاً لأهدافك الرياضية الفريدة',
        'home.quote.text': 'في لعبة اللياقة البدنية، كل تكرار هو زيادة في القوة، وكل مجموعة هي مستوى، وكل تمرين هو معركة زعيم. هل أنت مستعد لتصبح الشخصية الرئيسية في قصتك؟',
        'home.quote.author': '- الكابتن مؤمن',
        'home.badge.elite': 'مدرب نخبة',
        'home.badge.master': 'سيد اللياقة',
        'home.badge.level100': 'المستوى 100',

        // About Page
        'about.title': 'عن الكابتن مؤمن',
        'about.subtitle': 'مرشدك للمستوى التالي',
        'about.story': 'قصتي',
        'about.storyText1': 'لم تبدأ رحلتي في صالة الألعاب الرياضية، بل بدأت برغبة في فهم القدرات البشرية. بصفتي خريج كلية التربية الرياضية بجامعة المنصورة، جمعت بين الدقة الأكاديمية والتطبيق العملي.',
        'about.storyText2': 'على مر السنين، تطورت من مدرب محلي إلى مدير فرع في أفضل الصالات الرياضية، مدفوعاً دائماً بهدف واحد: مساعدة الآخرين على إطلاق العنان لوتهم الحقيقية.',
        'about.philosophy': 'فلسفة التدريب',
        'about.philosophy.scientific': 'منهج علمي',
        'about.philosophy.scientificDesc': 'أساليب تدريب قائمة على الأدلة مصممة لتحقيق أقصى قدر من الكفاءة والأمان.',
        'about.philosophy.mindset': 'العقلية أولاً',
        'about.philosophy.mindsetDesc': 'بناء المرونة العقلية لا يقل أهمية عن القوة البدنية.',
        'about.philosophy.sustainable': 'نتائج مستدامة',
        'about.philosophy.sustainableDesc': 'خلق تغييرات في نمط الحياة تستمر مدى الحياة، وليس لموسم واحد فقط.',
        'about.philosophy.holistic': 'نمو شامل',
        'about.philosophy.holisticDesc': 'التركيز على الصحة والأداء والجماليات بتوازن مثالي.',
        'about.experience': 'الخبرة',
        'about.certifications': 'الشهادات',
        'about.education': 'التعليم',
        'about.education.degree': 'التربية الرياضية',
        'about.education.school': 'كلية التربية الرياضية - جامعة المنصورة',
        'about.education.desc': 'تخصص في الإدارة الرياضية',

        // About - Timeline
        'about.timeline.branchManager': 'مدير فرع',
        'about.timeline.branchManagerDesc': 'قيادة العمليات في صالات Elegant و N13 Gyms، والإشراف على إدارة المرافق وتطوير الفريق.',
        'about.timeline.fitnessManager': 'مدير اللياقة البدنية',
        'about.timeline.fitnessManagerDesc': 'إدارة عمليات اللياقة البدنية ونجاح العملاء في Doctor and Coach.',
        'about.timeline.fitnessMgmt': 'إدارة اللياقة البدنية',
        'about.timeline.fitnessMgmtDesc': 'ترقيت لمدير اللياقة البدنية في Dr and Coach، وتوسعت في أدوار التدريب الشخصي في N13 و Elegant Gyms.',
        'about.timeline.coaching': 'التدريب الاحترافي',
        'about.timeline.coachingDesc': 'اكتسبت خبرة متنوعة عبر B1 Gym و Mego Gym، وتقدمت إلى مدير العمليات.',
        'about.timeline.founder': 'مؤسس Well and Fit',
        'about.timeline.founderDesc': 'تأسيس Well and Fit أثناء العمل كنائب لرئيس لجنة التعليم.',
        'about.timeline.online': 'إطلاق التدريب أونلاين',
        'about.timeline.onlineDesc': 'بدأت خدمات التدريب الشخصي عبر الإنترنت، للوصول إلى العملاء عالمياً.',

        // About - Certifications
        'about.cert.strength': 'أخصائي القوة والتكييف',
        'about.cert.strengthDesc': 'معتمد من TASS وأكاديمية PBLS، ومؤيد من الاتحاد المصري للثقافة الرياضية.',
        'about.cert.nutrition': 'مدرب تغذية رياضية',
        'about.cert.nutritionDesc': 'مبادئ التغذية الرياضية المتقدمة وتخطيط الوجبات',
        'about.cert.weight': 'إدارة الوزن',
        'about.cert.weightDesc': 'استراتيجيات متخصصة لفقدان الوزن المستدام وتكوين الجسم',
        'about.cert.cpr': 'الإسعافات الأولية والإنعاش القلبي الرئوي',
        'about.cert.cprDesc': 'معتمد من الهلال الأحمر المصري',

        // Services Page
        'services.title': 'اختر طريقك',
        'services.subtitle': 'اختر مستوى تدريبك وأطلق كامل إمكانياتك',
        'services.instantStart': 'بداية فورية',
        'services.provenResults': 'نتائج مثبتة',
        'services.support247': 'دعم على مدار الساعة',
        'services.mostPopular': 'الأكثر شعبية',
        'services.bestValue': 'أفضل قيمة',
        'services.whatsIncluded': 'ما يشمله البرنامج',
        'services.startQuest': 'ابدأ مهمتك',
        'services.xpBonus': 'مكافأة XP',
        'services.customQuest': 'تحتاج شيء مخصص؟',
        'services.customDescription': 'دعنا نصمم برنامج تدريب فريد مصمم خصيصاً لأهدافك وجدولك وتفضيلاتك.',
        'services.createCustom': 'إنشاء مهمة مخصصة',
        'services.warriorsTrained': 'محاربون تم تدريبهم',
        'services.yearsExperience': 'سنوات الخبرة',

        // Plans
        'plans.1month': 'مهمة شهر واحد',
        'plans.1monthSub': 'ابدأ أسطورتك',
        'plans.3months': 'بروتوكول 3 أشهر',
        'plans.3monthsSub': 'اصقل قوتك',
        'plans.6months': 'نظام 6 أشهر',
        'plans.6monthsSub': 'أتقن مصيرك',
        'plans.12months': 'الأسطوري 12 شهر',
        'plans.12monthsSub': 'كن خالداً',
        'plans.novice': 'مبتدئ',
        // Plans Details
        'plans.1month.desc': 'نقطة الانطلاق المثالية للمحاربين الطموحين. أتقن الأساسيات وابنِ قاعدتك.',
        'plans.3months.desc': 'برنامج متوسط مع تقنيات تدريب متقدمة ودعم تدريبي شخصي منتظم.',
        'plans.6months.desc': 'تدريب شامل للرياضيين المتفانين مع دعم ممتاز وبرمجة متقدمة.',
        'plans.12months.desc': 'تجربة VIP النهائية مع وصول غير محدود، تدريب يومي، ومزايا حصرية لأقصى قدر من النتائج.',

        // Plan Features
        'plans.feature.customProgram': 'برنامج تدريب مخصص',
        'plans.feature.nutrition': 'دليل تغذية مفصل',
        'plans.feature.tracking': 'تتبع التقدم الأسبوعي',
        'plans.feature.community': 'الوصول لمجتمع واتساب',
        'plans.feature.tutorials': 'فيديوهات شرح الأداء',
        'plans.feature.advancedPlans': 'خطط تدريب متقدمة',
        'plans.feature.mealPlans': 'خطط وجبات مخصصة',
        'plans.feature.checkins2x': 'متابعة مرتين أسبوعياً',
        'plans.feature.analysis': 'تحليل الأداء بالفيديو',
        'plans.feature.support247': 'دعم واتساب 24/7',
        'plans.feature.eliteProg': 'برمجة نخبة مخصصة',
        'plans.feature.advancedNut': 'تخطيط تغذية متقدم',
        'plans.feature.calls3x': '3 مكالمات تدريب أسبوعياً',
        'plans.feature.vipSupport': 'دعم VIP ذو أولوية',
        'plans.feature.recovery': 'دليل الاستشفاء والنوم',
        'plans.feature.legendaryPlans': 'خطط أسطورية مخصصة',
        'plans.feature.dailyCoaching': 'تدريب شخصي يومي',
        'plans.feature.eliteRecovery': 'نظام استشفاء النخبة',
        'plans.feature.privateLine': 'خط واتساب خاص',
        'plans.feature.vipBenefits': 'مزايا VIP حصرية',
        'plans.feature.bodyAnalysis': 'تحليل جسم شهري',

        // Coach Profile
        'coach.badges': 'الشارات',
        'coach.stats': 'الإحصائيات',
        'coach.badge.master': 'مدرب ماستر',
        'coach.badge.masterDesc': 'حالة أسطورية تم تحقيقها من خلال سنوات من التفاني',
        'coach.badge.strength': 'حكيم القوة',
        'coach.badge.strengthDesc': 'خبير في القوة والتكييف',
        'coach.badge.nutrition': 'عراب التغذية',
        'coach.badge.nutritionDesc': 'سيد التغذية الرياضية',
        'coach.badge.transformation': 'معلم التحول',
        'coach.badge.transformationDesc': 'أخصائي في تحولات الجسم الكاملة',
        'coach.badge.quest': 'سيد المهمات',
        'coach.badge.questDesc': 'مبتكر تحديات اللياقة الملحمية',
        'coach.stat.strength': 'القوة',
        'coach.stat.strengthDesc': 'سيد القوة والتقنية',
        'coach.stat.agility': 'الرشاقة',
        'coach.stat.agilityDesc': 'حركات سريعة ودقيقة',
        'coach.stat.endurance': 'التحمل',
        'coach.stat.enduranceDesc': 'طاقة لا تتوقف',
        'coach.stat.wisdom': 'الحكمة',
        'coach.stat.wisdomDesc': 'معرفة تدريبية نخبوية',
        'coach.unlockReq': 'متطلبات الفتح',
        'coach.achieve.warriors': 'محاربون تم تدريبهم',
        'coach.achieve.bossFights': 'معارك زعماء منتصرة',
        'coach.achieve.success': 'معدل النجاح',
        'coach.achieve.xp': 'نقاط الخبرة',
        'coach.achieve.years': '+8 سنوات',
        'coach.move.form': 'سيد الأداء المثالي',
        'coach.move.formDesc': 'تنفيذ التمارين بدقة متناهية',
        'coach.move.nutrition': 'استراتيجي التغذية',
        'coach.move.nutritionDesc': 'تصميم خطط وقود مثالية لأقصى أداء',
        'coach.move.mind': 'تزامن العقل والجسد',
        'coach.move.mindDesc': 'تحقيق تناغم كامل بين القوة الذهنية والجسدية',
        'coach.move.motivation': 'مضخم التحفيز',
        'coach.move.motivationDesc': 'رفع معنويات المحاربين لآفاق جديدة',
        'coach.title': 'الملف الشخصي',
        'coach.role': 'مدرب MA',
        'coach.expTitle': 'الخبرة',

        // Plan Highlights
        'plans.highlight.beginners': 'مثالي للمبتدئين',
        'plans.highlight.foundation': 'بناء الأساس',
        'plans.highlight.popular': 'الخيار الأكثر شعبية',
        'plans.highlight.transformations': 'تحولات حقيقية',
        'plans.highlight.athletes': 'للرياضيين الجادين',
        'plans.highlight.complete': 'تحول كامل',
        'plans.highlight.bestValue': 'أفضل قيمة',
        'plans.highlight.vip': 'معاملة VIP',

        // Training Page
        'training.title': 'مهمات ملحمية',
        'training.beta': 'تجريبي',
        'training.subtitle': 'ابدأ رحلة لياقتك من خلال تدريبات وتحديات بأسلوب الألعاب',
        'training.dailyQuests': 'مهمات يومية',
        'training.dailyQuestsDesc': 'تمارين يومية سريعة',
        'training.bossBattles': 'معارك الزعماء',
        'training.bossBattlesDesc': 'تحديات مكثفة',
        'training.achievementHunt': 'صيد الإنجازات',
        'training.achievementHuntDesc': 'افتح المكافآت',
        'training.skillTree': 'شجرة المهارات',
        'training.skillTreeDesc': 'تتبع التقدم',
        'training.launchingSoon': 'ينطلق قريباً',
        'training.launchingDesc': 'استعد لمغامرة لياقة ملحمية! انضم لمجتمعنا لتكون أول من يحصل على مهمات ومكافآت حصرية.',
        'training.joinCommunity': 'انضم للمجتمع',
        'training.phase1': 'مرحلة التطوير الأولى',

        // XP System Page
        'xp.title': 'نظام نقاط الخبرة',

        // Transformations Page
        'transformations.title': 'لوحة متصدري اللاعبين',
        'transformations.subtitle': 'شاهد التحولات الملحمية للاعبينا الأسطوريين',
        'transformations.journeyDetails': 'تفاصيل الرحلة',
        'transformations.program': 'البرنامج',
        'transformations.testimonial': 'شهادة اللاعب',
        'transformations.achievements': 'الإنجازات',
        'transformations.tapToSee': 'انقر لرؤية التفاصيل',
        'transformations.tapToFlip': 'انقر لرؤية التحول',
        'transformations.before': 'قبل',
        'transformations.after': 'بعد',
        // Transformation Data Keys
        'transformations.program.elite': 'نظام الأداء النخبة',
        'transformations.program.warrior': 'بروتوكول تدريب المحارب',
        'transformations.program.legendary': 'تحول أسطوري',
        'transformations.achieve.champion': 'بطل النخبة',
        'transformations.achieve.master': 'سيد التحول',
        'transformations.achieve.warrior': 'محارب النخبة',
        'transformations.achieve.legend': 'أسطورة اللياقة',
        'transformations.achieve.king': 'ملك التفاني',
        'transformations.achieve.star': 'نجم صاعد',
        'transformations.badge.weight': 'محارب الوزن',
        'transformations.badge.consistency': 'ملك الاستمرار',
        'transformations.badge.elite': 'نخبة التحول',
        'transformations.badge.muscle': 'باني العضلات',
        'transformations.badge.fatLoss': 'بطل حرق الدهون',
        'transformations.testi.1': 'كانت رحلة التحول مذهلة. أسلوب اللعب جعل كل تمرين مثيراً!',
        'transformations.testi.2': 'نتائج مذهلة مع البرنامج المنظم. حققت أكثر مما توقعت!',
        'transformations.testi.3': 'غيّر البرنامج ليس فقط جسمي، بل أسلوب حياتي بالكامل!',
        'xp.subtitle': 'تتبع تقدمك وافتح المكافآت',
        'xp.levelsAndTitles': 'المستويات والألقاب',
        'xp.howToEarnXp': 'كيف تكسب XP',
        'xp.earnXp': 'اكسب XP',
        'xp.levelUp': 'ارتقِ بمستواك',
        'xp.unlockRewards': 'افتح المكافآت',
        'xp.viewArsenal': 'عرض الترسانة الكاملة',
        'xp.scroll': 'مرر',
        'xp.currentLevel': 'المستوى الحالي',
        'xp.reward': 'المكافأة',
        'xp.rule1': 'ابدأ من المستوى 1 عند الاشتراك في أي باقة',
        'xp.rule2': 'كل باقة تمنحك نقاط XP لمساعدتك على التقدم',
        'xp.rule3': 'كل 10 مستويات، تفتح لقباً جديداً ومكافآت خاصة',
        'xp.rule4': 'تتبع تقدمك ونافس الآخرين على لوحة المتصدرين',
        'xp.heroTitle': 'رحلة محارب MA',
        'xp.heroSubtitle': 'أهلاً بك في MA Fitness، حيث تتحول رحلة لياقتك إلى تجربة لعب حقيقية!',
        'xp.benefitsTitle': 'لماذا ترتقي بالمستوى؟',
        'xp.benefit1': 'ألقاب حصرية تظهر في لوحة المتصدرين العالمية',
        'xp.benefit2': 'تيشيرت أو هودي مجاني كل 10 مستويات',
        'xp.benefit3': 'مستويات أعلى = قوة وعزيمة أكبر',
        'xp.benefit4': 'فرصة للظهور بين أفضل لاعبي MA Fitness',
        'xp.ctaTitle': 'مستعد لبدء رحلتك؟',
        'xp.ctaSubtitle': 'شاهد ترسانة باقات التدريب الكاملة واختر المسار المثالي لمهمتك الرياضية.',
        // Level Tier Titles
        'xp.tier.fitnessNovice': 'مبتدئ اللياقة',
        'xp.tier.maWarrior': 'محارب MA',
        'xp.tier.eliteTrainee': 'متدرب النخبة',
        'xp.tier.maLegend': 'أسطورة MA',
        'xp.tier.fitnessLeader': 'قائد اللياقة',
        'xp.tier.maKnight': 'فارس MA',
        'xp.tier.victoryMaster': 'سيد النصر',
        'xp.tier.maChampion': 'بطل MA',
        'xp.tier.fitnessBeast': 'وحش اللياقة',
        'xp.tier.maLegendElite': 'أسطورة MA النخبة',
        'xp.tier.supremeWarrior': 'المحارب الأعلى',
        'xp.tier.captainMA': 'كابتن MA',
        // Level Tier Rewards
        'xp.reward.gaining': 'اكتساب خبرة التمارين',
        'xp.reward.warriorTshirt': 'تيشيرت MA Warrior خاص',
        'xp.reward.hoodie': 'هودي MA للاعبين المتميزين',
        'xp.reward.specialTshirt': 'تيشيرت MA إصدار خاص',
        'xp.reward.limitedHoodie': 'هودي MA إصدار محدود',
        'xp.reward.newDesign': 'تيشيرت MA تصميم جديد',
        'xp.reward.levelHoodie': 'هودي MA خاص بالمستوى',
        'xp.reward.exclusiveTshirt': 'تيشيرت MA تصميم حصري',
        'xp.reward.champHoodie': 'هودي الأبطال MA',
        'xp.reward.topTshirt': 'تيشيرت MA من الدرجة الأولى',
        'xp.reward.vipHoodie': 'هودي VIP MA',
        'xp.reward.captain': 'حصري للكابتن مؤمن (MA)',

        // Contact Page
        'contact.joinAdventure': 'انضم للمغامرة',
        'contact.heroSubtitle': 'تواصل مع الكابتن مؤمن وابدأ رحلة لياقتك اليوم',
        'contact.title': 'تواصل معنا',
        'contact.partnerOrJoin': 'شاركنا أو انضم لفريقنا',
        'contact.startApplication': 'ابدأ التقديم',
        'contact.yourName': 'اسمك',
        'contact.email': 'البريد الإلكتروني',
        'contact.phone': 'الهاتف',
        'contact.message': 'رسالتك',
        'contact.requestType': 'نوع الطلب',
        'contact.partnership': 'شراكة',
        'contact.jobApplication': 'طلب توظيف',
        'contact.position': 'الوظيفة المطلوبة',
        'contact.experience': 'سنوات الخبرة',
        'contact.submit': 'تقديم الطلب',
        'contact.sending': 'جاري الإرسال...',
        'contact.followUs': 'تابعنا',
        'contact.followCoach': 'تابع الكابتن مؤمن',
        'contact.phName': 'أدخل اسمك',
        'contact.phEmail': 'أدخل بريدك الإلكتروني',
        'contact.phPhone': 'أدخل رقم هاتفك',
        'contact.phPosition': 'أدخل المسمى الوظيفي الذي تتقدم له',
        'contact.phExperience': 'أدخل سنوات خبرتك',
        'contact.phMessageJob': 'أخبرنا عن خبرتك ولماذا ستكون إضافة رائعة للفريق',
        'contact.phMessagePartner': 'أخبرنا عن فكرة الشراكة الخاصة بك',
        'contact.resume': 'السيرة الذاتية',
        'contact.success': 'تم إرسال رسالتك بنجاح! سنتصل بك قريباً.',
        'contact.error': 'حدث خطأ أثناء إرسال رسالتك. يرجى المحاولة مرة أخرى.',

        // Footer
        'footer.poweredBy': 'بدعم من',
        'footer.allRights': 'جميع الحقوق محفوظة',
        'footer.coachName': 'الكابتن مؤمن',
        'footer.quickLinks': 'روابط سريعة',
        'footer.followUs': 'تابعنا',

        // App Coming Soon Section
        'app.title1': 'مهمة جديدة',
        'app.title2': 'قيد التحميل',
        'app.subtitle': 'رفيق التدريب المحمول في طريقه إليك...',
        'app.levelUp': 'ارتقِ بمستواك',
        'app.fitnessApp': 'تطبيق اللياقة',
        'app.loading': 'جاري التحميل...',
        'app.progressXp': 'نقاط الخبرة',
        'app.progressXpDesc': 'تتبع تقدمك',
        'app.achievements': 'الإنجازات',
        'app.achievementsDesc': 'افتح المكافآت',
        'app.downloadOn': 'حمّل من',
        'app.appStore': 'آب ستور',
        'app.getItOn': 'احصل عليه من',
        'app.googlePlay': 'جوجل بلاي',
        'app.soon': 'قريباً',
        'app.getLaunchNotification': 'احصل على إشعار الإطلاق',
        'app.enterEmail': 'أدخل بريدك الإلكتروني',
        'app.notifyMe': 'أعلمني',
        'app.achievementUnlocked': 'تم فتح إنجاز!',
        'app.firstToKnow': 'ستكون أول من يعلم عند الإطلاق',

        // Common
        'common.learnMore': 'اعرف المزيد',
        'common.viewAll': 'عرض الكل',
        'common.getStarted': 'ابدأ الآن',
        'common.contactUs': 'تواصل معنا',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        // Check browser language or localStorage
        const saved = localStorage.getItem('language') as Language;
        if (saved && (saved === 'en' || saved === 'ar')) {
            setLanguage(saved);
        } else {
            const browserLang = navigator.language.startsWith('ar') ? 'ar' : 'en';
            setLanguage(browserLang);
        }
    }, []);

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === 'ar' }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export default LanguageContext;
